[platformio]
default_envs = photopainter

[env:photopainter]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  zinggjm/GxEPD2@^1.6.0
  adafruit/Adafruit GFX Library@^1.11.9
  bblanchon/ArduinoJson@^7.0.0
  adafruit/Adafruit SHTC3 Library@^1.0.1
  lewisxhe/XPowersLib@^0.2.6

[env:scan]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3
board_upload.flash_size = 16MB
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = -<*> +<scan_main.cpp>

[env:epdtest]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = -<*> +<epd_test.cpp>
lib_deps =
  zinggjm/GxEPD2@^1.6.0
  adafruit/Adafruit GFX Library@^1.11.9

[env:localtest]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = -<*> +<localtest.cpp> +<local_sensors.cpp>
lib_deps =
  adafruit/Adafruit SHTC3 Library@^1.0.1
  lewisxhe/XPowersLib@^0.2.6

[env:native]
platform = native
test_framework = unity
build_flags = -std=gnu++17
lib_deps = bblanchon/ArduinoJson@^7.0.0
test_build_src = yes
